# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImages',
            fields=[
                ('imgId', models.AutoField(primary_key=True, serialize=False)),
                ('imgPath', models.CharField(max_length=256)),
                ('isAppear', models.BooleanField(default=True)),
                ('imgName', models.CharField(max_length=100)),
                ('role', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address_line1', models.CharField(max_length=100, null=True)),
                ('address_line2', models.CharField(max_length=100, null=True)),
                ('mobilePhoneNumber', models.CharField(max_length=50, null=True)),
                ('phoneNumber', models.CharField(max_length=50, null=True)),
                ('role', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
