# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 06:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shopItemImgs')),
                ('itemName', models.CharField(max_length=100)),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('sale', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': '\uc0c1\ud488 \uc774\ubbf8\uc9c0',
                'verbose_name_plural': '\uc0c1\ud488 \uc774\ubbf8\uc9c0\ub4e4',
            },
        ),
        migrations.CreateModel(
            name='SliderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliderImages')),
                ('isAppear', models.BooleanField(default=True)),
                ('imgName', models.CharField(max_length=100)),
                ('role', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': '\uba54\uc778 \uc2ac\ub77c\uc774\ub354 \uc774\ubbf8\uc9c0',
                'verbose_name_plural': '\uba54\uc778 \uc2ac\ub77c\uc774\ub354 \uc774\ubbf8\uc9c0\ub4e4',
            },
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address_line1', models.CharField(max_length=100, null=True)),
                ('address_line2', models.CharField(max_length=100, null=True)),
                ('mobilePhoneNumber', models.CharField(max_length=50, null=True)),
                ('phoneNumber', models.CharField(max_length=50, null=True)),
                ('role', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
