# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='shopItemImgs')),
            ],
        ),
        migrations.AlterModelOptions(
            name='sliderimages',
            options={'verbose_name': '\uba54\uc778 \uc2ac\ub77c\uc774\ub354 \uc774\ubbf8\uc9c0', 'verbose_name_plural': '\uba54\uc778 \uc2ac\ub77c\uc774\ub354 \uc774\ubbf8\uc9c0\ub4e4'},
        ),
    ]
