# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shopItem',
        ),
    ]
