# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_delete_shopitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_line3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
