# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20160720_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimages',
            name='imgPath',
        ),
        migrations.AddField(
            model_name='sliderimages',
            name='image',
            field=models.ImageField(default=datetime.datetime(2016, 7, 20, 6, 48, 58, 983000, tzinfo=utc), upload_to='sliderImages'),
            preserve_default=False,
        ),
    ]
