# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_sliderimages_imgname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopitem',
            options={'verbose_name': '\uc0c1\ud488 \uc774\ubbf8\uc9c0', 'verbose_name_plural': '\uc0c1\ud488 \uc774\ubbf8\uc9c0\ub4e4'},
        ),
        migrations.RenameField(
            model_name='shopitem',
            old_name='img',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='id',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='isSale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='itemId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopitem',
            name='itemName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopitem',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
