# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='singcontents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='singcontents')),
                ('text', models.CharField(max_length=200)),
                ('source', models.URLField(max_length=300)),
            ],
        ),
    ]
