# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_auto_20160728_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='doccontents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='docucontents')),
                ('text', models.TextField(default='')),
                ('docuimg', models.ImageField(upload_to='docuimg')),
            ],
        ),
        migrations.RenameField(
            model_name='singcontents',
            old_name='video',
            new_name='file',
        ),
    ]
