# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_auto_20160729_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doccontents',
            options={'verbose_name': '\uad50\uc721 \uac00\uc774\ub4dc', 'verbose_name_plural': '\uad50\uc721 \uac00\uc774\ub4dc \ub2e4\uc6b4\ub85c\ub4dc'},
        ),
        migrations.AlterModelOptions(
            name='singcontents',
            options={'verbose_name': '\ub3d9\uc694 \uc790\ub8cc', 'verbose_name_plural': '\ub3d9\uc694 \ub2e4\uc6b4\ub85c\ub4dc'},
        ),
    ]
