# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0004_auto_20160801_1519'),
        ('download', '0004_auto_20160801_1516'),
    ]

    operations = [
    ]
