# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shopItemImgs')),
                ('itemName', models.CharField(max_length=100)),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('sale', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': '\uc0c1\ud488 \uc774\ubbf8\uc9c0',
                'verbose_name_plural': '\uc0c1\ud488 \uc774\ubbf8\uc9c0\ub4e4',
            },
        ),
    ]
