# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 02:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivername', models.CharField(max_length=10)),
                ('receiverphonenumber', models.IntegerField()),
                ('receiveraddress', models.CharField(max_length=100)),
                ('receiverphonenumber2', models.CharField(max_length=100)),
                ('itemlist', models.TextField(max_length=500)),
                ('cost', models.IntegerField()),
                ('require', models.TextField(max_length=100)),
                ('ispay', models.BooleanField(default=False)),
                ('isreceive', models.BooleanField(default=False)),
                ('howToPay', models.CharField(max_length=50)),
                ('paymodelid', models.IntegerField(default=0)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\uc720\uc800\ubcc4 \ud604\uc7ac \uc9c4\ud589\uc911\uc778 \uacb0\uc81c\ub0b4\uc5ed',
                'verbose_name_plural': '\uc720\uc800\ubcc4 \ud604\uc7ac \uc9c4\ud589\uc911\uc778 \uacb0\uc81c\ub0b4\uc5ed\ub4e4',
            },
        ),
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivername', models.CharField(max_length=10)),
                ('receiverphonenumber', models.IntegerField()),
                ('receiveraddress', models.CharField(max_length=100)),
                ('receiverphonenumber2', models.CharField(max_length=100)),
                ('itemlist', models.TextField(max_length=500)),
                ('cost', models.IntegerField()),
                ('require', models.TextField(max_length=100)),
                ('ispay', models.BooleanField(default=False)),
                ('isreceive', models.BooleanField(default=False)),
                ('howToPay', models.CharField(max_length=50)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\uacb0\uc81c\uac74',
                'verbose_name_plural': '\uacb0\uc81c \ud56d\ubaa9\ub4e4 ',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shopItemImgs/item')),
                ('content', models.TextField()),
                ('makeTime', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\uc0c1\ud488 \ub313\uae00',
                'verbose_name_plural': '\uc0c1\ud488 \ub313\uae00\ub4e4 ',
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='shopItemImgs/item')),
                ('detailImage', models.ImageField(default=None, upload_to='shopItemImgs/detail')),
                ('itemName', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('stock', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('sale', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('category', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '\uc0c1\ud488',
                'verbose_name_plural': '\uc0c1\ud488\ub4e4',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='itemNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ShopItem'),
        ),
    ]
