# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20160802_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopitem',
            options={'verbose_name': '\uc0c1\ud488', 'verbose_name_plural': '\uc0c1\ud488\ub4e4'},
        ),
        migrations.AddField(
            model_name='shopitem',
            name='category',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='itemNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ShopItem'),
        ),
    ]
