# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_review_delpw'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
