# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20160803_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='category',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='itemNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ShopItem'),
        ),
        migrations.AlterField(
            model_name='review',
            name='makeTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='sale',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
