# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 04:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_auto_20160803_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivername', models.TextField()),
                ('receiverphonenumber', models.IntegerField()),
                ('receiveraddress', models.TextField(max_length=100)),
                ('receiverphonenumber2', models.IntegerField()),
                ('itemlist', models.TextField(max_length=500)),
                ('cost', models.IntegerField()),
                ('require', models.TextField(max_length=100)),
                ('ispay', models.BooleanField(default=False)),
                ('isreceive', models.BooleanField(default=False)),
                ('howToPay', models.TextField(max_length=50)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\uacb0\uc81c\uac74',
                'verbose_name_plural': '\uacb0\uc81c \ud56d\ubaa9\ub4e4 ',
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='itemNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ShopItem'),
        ),
    ]
