# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 05:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20160803_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qna',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 3, 14, 55, 43, 871158)),
        ),
    ]
