# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sliderImages',
            fields=[
                ('imgId', models.AutoField(primary_key=True, serialize=False)),
                ('imgPath', models.ImageField(upload_to='attoHome/')),
                ('imgName', models.CharField(max_length=100)),
            ],
        ),
    ]
