# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_sliderimages_isappear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimages',
            name='imgPath',
            field=models.CharField(max_length=256),
        ),
    ]
