# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20160711_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address_line1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_line2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobilePhoneNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phoneNumber',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
