# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 01:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20160722_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterModelOptions(
            name='shopitem',
            options={'verbose_name': '\uc0c1\ud488 \uc774\ubbf8\uc9c0', 'verbose_name_plural': '\uc0c1\ud488 \uc774\ubbf8\uc9c0\ub4e4'},
        ),
        migrations.AlterModelOptions(
            name='sliderimages',
            options={'verbose_name': '\uba54\uc778 \uc2ac\ub77c\uc774\ub354 \uc774\ubbf8\uc9c0', 'verbose_name_plural': '\uba54\uc778 \uc2ac\ub77c\uc774\ub354 \uc774\ubbf8\uc9c0\ub4e4'},
        ),
        migrations.RenameField(
            model_name='shopitem',
            old_name='img',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='id',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='isSale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='itemId',
            field=models.AutoField(default=datetime.datetime(2016, 7, 25, 1, 50, 38, 294000, tzinfo=utc), primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopitem',
            name='itemName',
            field=models.CharField(default=datetime.datetime(2016, 7, 25, 1, 50, 56, 766000, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopitem',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
