# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20160711_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(null=True),
        ),
    ]
