# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 05:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('makeTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='newsImages/default.jpg', upload_to='newsImages')),
                ('headLine', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('contentsImg', models.ImageField(blank=True, upload_to='newsImages')),
                ('contentsLink', models.CharField(max_length=200)),
                ('makeTime', models.DateTimeField(auto_now_add=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('commentsCnt', models.PositiveSmallIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='postNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Posts'),
        ),
    ]
