# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='contentsImg',
            field=models.ImageField(null=True, upload_to='newsImages'),
        ),
    ]
