# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_posts_contentsimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='contentsImg',
            field=models.ImageField(blank=True, upload_to='newsImages'),
        ),
    ]
