# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20160728_1407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coments',
            new_name='Comments',
        ),
    ]
